### ISSUE TITLE
Current .dmg file does not include the 2020 game

### ISSUE THREAD

**Issue by lospugs** [sjcbulldog/xeropathgen#28]
Just downloaded the latest (today, 7 Jan) and the .dmg app bundle only has the 2018 and 2019 game bundles.

<img width="982" alt="Screen Shot 2020-01-07 at 4 13 42 PM" src="https://user-images.githubusercontent.com/25273125/71929953-bcac7500-3168-11ea-8057-dd97db8326b0.png">

**Comment by Diverjim84** [comment]
I would love this to be updated to include the new game.  Love this app. Actually works unlike path weaver...

**Comment by sjcbulldog** [comment]
The mac version lags in time somewhat.  I have a MAC but it is not my strongest platform.  I'll get it updated tonight and post a new DMG.

Thanks

**Comment by sjcbulldog** [comment]
I am going to work on the getting a new MAC OS build with the 2020 fields.  But this will not start until tonight once I am done with work.  However, while I do this, if you take the two files from the fields directory that start with 2020 (e.g. fields/2020-field.jpg and fields/2020-infinite.json) and copy them to YOURHOMEDIRECTORY/Library/Application Support/ErrorCodeXero/XeroPathGenerator/fields, you should then have 2020 field support.  The new build will just also include a few minor bug fixes since the last Mac OS build.

**Comment by sjcbulldog** [comment]
New MacOS version is up.  Only tested on Catalina since that’s all I have.

**Comment by Diverjim84** [comment]
You are amazing!  Thank you!  I would love to learn about the math behind this in the off season.  Do you have anything on the how's of this?  I'm a sw mentor here in AL.

**Comment by sjcbulldog** [comment]
Where in Alabama?  Look at the documentation of the program as well as www.xerosw.org.

**Comment by Diverjim84** [comment]
Huntsville al, you going to a regional near by?

**Comment by sjcbulldog** [comment]
No, I’m in Portland OR, but grew up in meridian ms, graduated from Mississippi state, and have a sister that lives in Athens AL.

**Comment by sjcbulldog** [comment]
Note, the math was mostly stolen from Jaci Path and the Cheesy Poofs by reverse engineering their code.  Once I understood it, it was fairly straight forward, but it was an effort to get up to speed.  The site www.xerosw.org is our team WIKI.  Most of it (all but this years robot) is public and we put all of our training materials there.  It has a long way to go, but we work on it when we can.

**Comment by Diverjim84** [comment]
Small world! I’m bookmarking your sites for my kids.  It’s been a rough year for them as I haven’t been able to do a software off season.  My main team is Morgan county so its a 45min drive one way and my life has been upside down for the last 9 months.

**Comment by Diverjim84** [comment]
What is the insert key substitute for the Mac version?  Trying to add waypoints.  Thanks

**Comment by Diverjim84** [comment]
Am I correct in thinking that to run a trajectory in reverse, I just multiply v by -1 and run the trajectory from bottom to top (except with time)?

**Comment by sjcbulldog** [comment]
I have not tried to run a trajectory from the end to the beginning. I would have to work through the math.  I have run a trajectory from front to back but with the robot driving in reverse.  In that case you just invert the velocities, positions, accelerations and invert the heading angles.

**Comment by Diverjim84** [comment]
You use all that?  Motion profile on srx only needs position, velocity, and time to execute.  Unless im missing something.  This is my first year trying this.

**Comment by sjcbulldog** [comment]
I’m not sure on the insert key for Mac. I use a pc.  But insert waypoint is on the edit menu when a path is selected.  We run the path follower loops on the roborio.  Our follower uses a PDVA where P and D are the traditional values from a PID controller. The V and A values are feed forward terms for velocity and acceleration.
