### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by DKassab1425** [sjcbulldog/xeropathgen#5]
After a new path group is created, the app crashes when either the demo it turned on or a new path is created.

**Comment by sjcbulldog** [comment]
The crash when you select demo is a problem with the button.  It should not be enabled if there is no path under the group.  This is an easy fix.  However, I cannot reproduce the crash when you select a new path after a new group is created.  Can you detail exactly what you where doing?

Was it as simple as:
1. Start Program
2. Select Edit/Add Path Group
3. Select Edit/Add Path
4. Program crashes ????

**Comment by sjcbulldog** [comment]
Also, when you select the Help/About menu item, what is the build number?

**Comment by DKassab1425** [comment]
It is as you described, I open the app, edit, new path group, edit, new path, then it crashes.
the current build is 1.0.1.2

**Comment by sjcbulldog** [comment]
The problem was that a robot with no name was created.  I put a check in that when you create a robot, a name must be given of the robot is not created.
