### ISSUE TITLE
field viewing

### ISSUE THREAD

**Issue by DKassab1425** [sjcbulldog/xeropathgen#6]
when a game is selected, no field is displayed.

**Comment by sjcbulldog** [comment]
Is a field displayed when the program first starts?  Does it go away when a new game is selected?

**Comment by DKassab1425** [comment]
sorry I should have been more specific. A field is never displayed and changing the game does not start displaying one.

**Comment by sjcbulldog** [comment]
For small screens, the bottom window was too big, hiding the field window.

**Comment by sjcbulldog** [comment]
What I have done, is if the top or bottom windows on the left side get below a minimum size, I force a window layout where both get half of the screen size.
